# Generated by Django 3.0.8 on 2020-07-01 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_start', models.DateTimeField()),
                ('water_deration', models.DateTimeField()),
                ('water_finish', models.DateTimeField()),
                ('last_water', models.DateTimeField()),
                ('next_water', models.DateTimeField()),
            ],
        ),
    ]
