# Generated by Django 3.1 on 2020-08-11 14:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterPump',
            fields=[
                ('id', models.AutoField(auto_created=True,primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_status', models.CharField(
                    default='stop', max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_start', models.TimeField(default=django.utils.timezone.now)),
                ('water_deration', models.TimeField(default=django.utils.timezone.now)),
                ('water_finish', models.TimeField(default=django.utils.timezone.now)),
                ('next_water', models.TimeField(default=django.utils.timezone.now)),
                ('water_start_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
