# Generated by Django 3.1 on 2020-08-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='water',
            name='how_often',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='water',
            name='next_water',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='water',
            name='water_deration',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='water',
            name='water_finish',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='water',
            name='water_start',
            field=models.TimeField(default=0),
        ),
        migrations.AlterField(
            model_name='water',
            name='water_start_date',
            field=models.DateField(default=0),
        ),
    ]
