# Generated by Django 3.0.8 on 2020-07-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_auto_20200702_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='last_water',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='water',
            name='next_water',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='water',
            name='water_deration',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='water',
            name='water_finish',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='water',
            name='water_start',
            field=models.DateTimeField(default=None),
        ),
    ]
