# Generated by Django 3.1 on 2020-08-23 19:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0002_auto_20200813_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='water',
            name='gpio_pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='waterpump',
            name='gpio_pin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='waterpump',
            name='pump_finish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='waterpump',
            name='pump_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
