# Generated by Django 3.0.8 on 2020-07-04 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0004_auto_20200702_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='water',
            old_name='last_water',
            new_name='how_often',
        ),
    ]
