# Generated by Django 3.0.8 on 2020-07-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0005_auto_20200704_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='how_often',
            field=models.IntegerField(default=0),
        ),
    ]
