# Generated by Django 3.1 on 2020-08-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0007_waterpump'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterpump',
            name='pump_status',
            field=models.TextField(default='stop'),
        ),
    ]
