# Generated by Django 3.1 on 2020-08-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0008_auto_20200808_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterpump',
            name='pump_status',
            field=models.CharField(default='stop', max_length=225),
        ),
    ]
