# Generated by Django 3.1 on 2020-08-08 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0009_auto_20200808_1719'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='water',
            table='water_schedule',
        ),
        migrations.AlterModelTable(
            name='waterpump',
            table='water_pump',
        ),
    ]
