# Generated by Django 3.1 on 2020-08-08 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('water', '0010_auto_20200808_1804'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='water',
            table=None,
        ),
        migrations.AlterModelTable(
            name='waterpump',
            table=None,
        ),
    ]
