version: '3'

services:
  web:
    build: ./arc
    command: python manage.py runserver 0.0.0.0:8000
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/mem:/dev/mem"
    privileged: true
    volumes:
      - ./arc/:/usr/src/app/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: redis:alpine
    expose:
      - '6379'
    ports:
      - '6379:6379'

  celery:
    build: ./arc
    command: celery -A arc worker -l info
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/mem:/dev/mem"
    privileged: true
    volumes:
      - ./arc/:/usr/src/app/
    links:
      - redis
    depends_on:
      - db
      - redis

  celery-beat:
    build: ./arc
    command: celery -A arc beat -l info
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/mem:/dev/mem"
    privileged: true
    volumes:
      - ./arc/:/usr/src/app/
    links:
      - redis
    depends_on:
      - db
      - redis