version: '3'

services:
  web:
    restart: always
    build: ./arc
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; python /code/manage.py makemigrations && python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/mem:/dev/mem"
    privileged: true
    volumes:
      - ./arc/:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=pi
      - POSTGRES_PASSWORD=rnautomations
      - POSTGRES_DB=arc_db
    ports:
      - "5433:5432"
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:alpine
    expose:
      - '6379'
    ports:
      - '6379:6379'
    volumes:
     - redisdata:/data

  celery:
    restart: always
    build: ./arc
    command: celery -A arc worker -Q queue_humidity -c 2 -l info
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/mem:/dev/mem"
    privileged: true
    volumes:
      - ./arc/:/code/
    links:
      - redis
    depends_on:
      - db
      - redis
      - web

  celery-beat:
    restart: always
    build: ./arc
    command: celery -A arc beat -l info
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/mem:/dev/mem"
    privileged: true
    volumes:
      - ./arc/:/code/
    links:
      - redis
    depends_on:
      - db
      - redis
      - web

volumes:
    pgdata:
    redisdata:
