version: '3'

services:
  web:
    restart: always
    build: ./arc
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; python /arc/manage.py collectstatic --noinput && python /arc/manage.py makemigrations && python /arc/manage.py migrate --noinput && gunicorn arc.wsgi:application --bind 0.0.0.0:8000"
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/mem:/dev/mem"
    privileged: true
    expose: 
      - 8000
    volumes:
      - ./arc:/arc
      - static_volume:/arc/static  # <-- bind the static volume
      - media_volume:/arc/media  # <-- bind the media volume
    networks:  # <-- here
      - nginx_network
      - db_network  # <-- connect to the bridge
      - redis_network  # <-- connect to the bridge
    depends_on:
      - db
      - redis

  nginx:
    build: ./nginx
    volumes:
      - ./arc:/arc
      - static_volume:/arc/static  # <-- bind the static volume
      - media_volume:/arc/media  # <-- bind the media volume

    ports:
      - 8000:80
    depends_on:
      - web
    networks:  # <-- here
      - nginx_network

  db:
    restart: always
    image: postgres
    environment:
      - POSTGRES_USER=pi
      - POSTGRES_PASSWORD=rnautomations
      - POSTGRES_DB=arc_db
    ports:
      - "5433:5432"
    networks:  # <-- connect to the bridge
      - db_network
      - redis_network

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:alpine
    expose:
      - '6379'
    ports:
      - '6379:6379'
    networks:  # <-- connect to the bridge
      - redis_network
    volumes:
     - redisdata:/data

  celery:
    restart: always
    build: ./arc
    command: bash -c "celery -A arc worker -Q queue_humidity -c 2 -l info && celery -A arc worker --concurrency=2"
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/mem:/dev/mem"
    privileged: true
    volumes:
      - ./arc:/arc
    links:
      - redis
    depends_on:
      - db
      - redis
      - web

  celery-beat:
    restart: always
    build: ./arc
    command: celery -A arc beat -l info
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/mem:/dev/mem"
    privileged: true
    volumes:
      - ./arc:/arc
    links:
      - redis
    depends_on:
      - db
      - redis
      - web

networks:  # <-- and here
  nginx_network:
    driver: bridge
  db_network:  # <-- add the bridge
    driver: bridge
  redis_network:  # <-- add the bridge
    driver: bridge

volumes:
    pgdata:
    redisdata:
    static_volume:
    media_volume:
