version: '3'

services:
  web:
    build: ./arc
    command: bash -c "while !</dev/tcp/db/5432; do sleep 1; done; python /code/manage.py makemigrations && python /code/manage.py migrate --noinput && python /code/manage.py runserver 0.0.0.0:8000"
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/mem:/dev/mem"
    privileged: true
    volumes:
      - ./arc/:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  redis:
    image: redis:alpine
    expose:
      - '6379'
    ports:
      - '6379:6379'

  celery:
    build: ./arc
    command: celery -A arc worker -l info --concurrency=4
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/mem:/dev/mem"
    privileged: true
    volumes:
      - ./arc/:/code/
    links:
      - redis
    depends_on:
      - db
      - redis
      - web

  celery-beat:
    build: ./arc
    command: celery -A arc beat -l info
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/mem:/dev/mem"
    privileged: true
    volumes:
      - ./arc/:/code/
    links:
      - redis
    depends_on:
      - db
      - redis
      - web