# Generated by Django 3.1 on 2020-09-06 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(default=0)),
                ('deration', models.TimeField(default=0)),
                ('finish', models.TimeField(default=0)),
                ('next_schedule', models.TimeField(default=0)),
                ('start_date', models.DateField(default=0)),
                ('how_often', models.TimeField(default=0)),
                ('gpio_pin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WaterPump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pump_status', models.CharField(default='stop', max_length=225)),
                ('pump_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('pump_finish', models.DateTimeField(default=django.utils.timezone.now)),
                ('gpio_pin', models.IntegerField(default=0)),
            ],
        ),
    ]
