# Generated by Django 3.1 on 2020-11-15 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relay_state', models.CharField(default='False', max_length=225)),
                ('task_id', models.CharField(default='False', max_length=225)),
                ('relay_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('relay_finish', models.DateTimeField(default=django.utils.timezone.now)),
                ('gpio_pin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Relay14',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relay_state', models.CharField(default='False', max_length=225)),
                ('task_id', models.CharField(default='False', max_length=225)),
                ('relay_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('relay_finish', models.DateTimeField(default=django.utils.timezone.now)),
                ('gpio_pin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Relay15',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relay_state', models.CharField(default='False', max_length=225)),
                ('task_id', models.CharField(default='False', max_length=225)),
                ('relay_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('relay_finish', models.DateTimeField(default=django.utils.timezone.now)),
                ('gpio_pin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(blank=True, null=True)),
                ('deration', models.TimeField(blank=True, null=True)),
                ('finish', models.TimeField(blank=True, null=True)),
                ('finish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_schedule', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('how_often', models.TimeField(blank=True, null=True)),
                ('run_time', models.TimeField(blank=True, null=True)),
                ('gpio_pin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(blank=True, null=True)),
                ('deration', models.TimeField(blank=True, null=True)),
                ('finish', models.TimeField(blank=True, null=True)),
                ('finish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_schedule', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('how_often', models.TimeField(blank=True, null=True)),
                ('run_time', models.TimeField(blank=True, null=True)),
                ('gpio_pin', models.IntegerField(default=0)),
            ],
        ),
    ]
