# Generated by Django 3.2.4 on 2021-07-01 04:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(blank=True, null=True)),
                ('deration', models.TimeField(blank=True, null=True)),
                ('finish', models.TimeField(blank=True, null=True)),
                ('finish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_schedule', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('how_often', models.TimeField(blank=True, null=True)),
                ('run_time', models.TimeField(blank=True, null=True)),
                ('gpio_pin', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField(blank=True, null=True)),
                ('deration', models.TimeField(blank=True, null=True)),
                ('finish', models.TimeField(blank=True, null=True)),
                ('finish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('next_schedule', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('how_often', models.TimeField(blank=True, null=True)),
                ('run_time', models.TimeField(blank=True, null=True)),
                ('gpio_pin', models.IntegerField(default=0)),
            ],
        ),
    ]
