# Generated by Django 3.1 on 2021-01-22 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relay',
        ),
        migrations.DeleteModel(
            name='Relay14',
        ),
        migrations.DeleteModel(
            name='Relay15',
        ),
    ]
