# Generated by Django 3.2.4 on 2021-08-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='schedule_interval',
            field=models.TimeField(default='00:00:00', null=True),
        ),
    ]
