# Generated by Django 3.1 on 2020-10-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterpump',
            name='pump_status',
            field=models.CharField(default='False', max_length=225),
        ),
    ]
