# Generated by Django 3.2.4 on 2021-07-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelayStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(default='')),
                ('gpio_pin', models.IntegerField(default=0)),
            ],
        ),
    ]
