# Generated by Django 3.2.4 on 2021-08-01 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_alter_schedule_schedule_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='duration',
            field=models.DurationField(default='00:00:00', null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='schedule_interval',
            field=models.DurationField(default='00:00:00', null=True),
        ),
    ]
