# Generated by Django 3.2.4 on 2021-07-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_relaystatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relaystatus',
            old_name='status',
            new_name='button_status',
        ),
        migrations.AddField(
            model_name='relaystatus',
            name='schedule_status',
            field=models.TextField(default=''),
        ),
    ]
