# Generated by Django 3.1 on 2020-11-12 00:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20201111_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='next_schedule',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
