# Generated by Django 3.2.4 on 2021-07-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20210727_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relaystatus',
            name='button_status',
            field=models.TextField(default='True'),
        ),
        migrations.AlterField(
            model_name='relaystatus',
            name='schedule_status',
            field=models.TextField(default='False'),
        ),
    ]
