# Generated by Django 3.2.4 on 2021-08-01 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20210731_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulelog',
            name='finish',
        ),
        migrations.RemoveField(
            model_name='schedulelog',
            name='how_often',
        ),
        migrations.RemoveField(
            model_name='schedulelog',
            name='run_time',
        ),
        migrations.AlterField(
            model_name='schedulelog',
            name='duration',
            field=models.DurationField(default='00:00:00', null=True),
        ),
    ]
