# Generated by Django 3.2.4 on 2021-07-29 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20210727_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='deration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='schedulelog',
            old_name='deration',
            new_name='duration',
        ),
    ]
