# Generated by Django 3.1 on 2020-11-12 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20201111_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='next_schedule',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
