# Generated by Django 3.2.4 on 2021-07-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20210728_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='duration',
            field=models.TimeField(default='00:00:00', null=True),
        ),
    ]
