# Generated by Django 3.1 on 2020-11-12 00:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20201111_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='next_schedule',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
