# Generated by Django 3.1 on 2020-11-12 01:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20201111_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='finish_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
