# Generated by Django 3.1 on 2020-11-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_schedule_finish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='relay14',
            name='task_id',
            field=models.CharField(default='False', max_length=225),
        ),
        migrations.AddField(
            model_name='relay15',
            name='task_id',
            field=models.CharField(default='False', max_length=225),
        ),
    ]
