# Generated by Django 3.1 on 2020-08-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humidity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humiditytemp',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='humiditytemp',
            name='temp',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
