# Generated by Django 3.2.4 on 2021-08-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humidity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humiditytemp',
            name='humidity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='humiditytemp',
            name='temp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='humiditytempvalues',
            name='buffer_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='humiditytempvalues',
            name='humidity_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='humiditytempvalues',
            name='temp_value',
            field=models.IntegerField(default=0),
        ),
    ]
