# Generated by Django 3.2.4 on 2021-07-31 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humidity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhaust',
            name='automation_status',
            field=models.TextField(default=''),
        ),
    ]
