# Generated by Django 3.1 on 2020-10-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humidity', '0002_humiditytempvalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humiditytemp',
            name='humidity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='humiditytemp',
            name='temp',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='humiditytempvalues',
            name='humidity_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='humiditytempvalues',
            name='temp_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
