# Generated by Django 3.1 on 2021-02-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('humidity', '0002_exhust'),
    ]

    operations = [
        migrations.AddField(
            model_name='humiditytempvalues',
            name='buffer_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
